### ISSUE TITLE
TeemIP Network Management Extended brake vSphere Data Collector

### ISSUE THREAD

**Issue by furynick** [TeemIp/teemip-network-mgmt-extended#1]
vSphere Data collector seems to be incompatible with teemip-network-mgmt-extended as this extension redefines LogicalInterface:speed attribute into reference to InterfaceSpeed Class.

```
[2021-08-25 11:17:33] [Error] Failed to update the Synchro Data Source. Inconsistent data model, the attribute 'speed' does not exist in iTop.
```

https://sourceforge.net/p/itop/tickets/1997/

**Comment by xtophe38** [comment]
Sorry for de delayed answer. You are right. I'll need to review the different collectors so that they support the extension. This should be hopefully be done around  end of Q1 22 / early Q2 22.

**Comment by 4franz** [comment]
with the ocs collector you face the same problem:
[Error]	Failed to update the Synchro Data Source. Inconsistent data model, the attribute 'speed' does not exist in iTop.

**Comment by 2confirm** [comment]
I ran into the same error. Any update on this yet? Or is there a workaround?

**Comment by xtophe38** [comment]
Finally...  I've just submitted the following [PR ](https://github.com/Combodo/itop-data-collector-vsphere/pull/3) on [itop-data-collector-vsphere](https://github.com/Combodo/itop-data-collector-vsphere) to have that bug fixed.

**Comment by Hipska** [comment]
@xtophe38 That PR is closed, what is the status of this issue now?

**Comment by xtophe38** [comment]
@hipska It should be resolved. I'll double check before closing the issue.

**Comment by xtophe38** [comment]
@Hipska The PR that I'm refering to, on the [above comment](https://github.com/TeemIp/teemip-network-mgmt-extended/issues/1#issuecomment-1255260794), has been closed because work had started to restructure the itop-data-collector-base. I had open branch [5544](https://github.com/Combodo/itop-data-collector-vsphere/tree/issue/5544) to work on the subject but work has not been complete, yet ! Bottom line: I need to check with Combodo team how we can move forward on the subject and possibly release a new version of the collector that solves the issue.

**Comment by xtophe38** [comment]
Work on the vSphere collector is in progress. A new release will be available before the end of January 2024.

**Comment by GlebDen** [comment]
as workaround:
try to change in combodo-data-collector-for-vsphere/collectors/vSphereLogicalInterfaceCollector.json
"attcode": "speed",  ->"attcode": "interfacespeed_id",

**Comment by xtophe38** [comment]
> as workaround: try to change in combodo-data-collector-for-vsphere/collectors/vSphereLogicalInterfaceCollector.json "attcode": "speed", ->"attcode": "interfacespeed_id",

This will be automatically handled by the next version of the vSphere collector.

**Comment by xtophe38** [comment]
Revision 1.2.0 of the "Data collector for vSphere" that has been released on the 22nd of January and that you can get [here](https://store.itophub.io/en_US/products/combodo-data-collector-for-vsphere), on iTop Hub, now correctly handles the different TeemIP extensions that may be installed or activated.

As a consequence, I'm closing this issue. Thanks to all for you patience.
