### ISSUE TITLE
Cannot install extension

### ISSUE THREAD

**Issue by MikeW83** [TeemIp/teemip-network-mgmt-extended#2]
I have a fresh installation of Version 3.0.0-8663 and tried to install the extension via iTop Hub. But I receive this dependency error:
![image](https://user-images.githubusercontent.com/35097389/163397253-43b2b6ef-dd32-4e78-82c9-f2943c9febbf.png)

I have installed production environment with all ITIL options enabled without demo data. What's wrong with my installation?

Best regards, Michael

**Comment by xtophe38** [comment]
Sorry for the delayed answered.

I guess that you didn't install the "IPAM for iTop" alias "teemip-core-ip-mgmt" extension that is a dependancy for "teemip-network-mgmt-extended". It is available form the Hub as well.
