### ISSUE TITLE
Fail to upgrade teemip-network-mgmt-extended 3.1.0 on iTop 3.1.0

### ISSUE THREAD

**Issue by snapet** [TeemIp/teemip-network-mgmt-extended#8]
Hi, I get below error when trying to upgrade on iTop 3.1.0. This happens when upgrading manually by first unzipping in the extensions directory as well as via itop hub. Which probably is normal but, just for your information.

Tried on php 7.4 and 8.1. 
iTop version is 3.1.0-2-11973. 
Database is  MySQL: 10.11.5-MariaDB-3. 
Currently on PHP  8.1.12

This is the error I get:
`Error loading module "teemip-network-mgmt-extended": /itop_design/menus/menu[ConfigManagementOverview]/definition/cells/cell[teemip-000] at line 1600: could not be found - Loaded modules: dictionaries:1.0, core:1.0, application:1.0, authent-cas:3.1.0, authent-external:3.1.0, authent-ldap:3.1.0, authent-local:3.1.0, combodo-backoffice-darkmoon-theme:3.1.0, combodo-password-expiration:1.0.1, itop-attachments:3.1.0, itop-backup:3.1.0, itop-config:3.1.0, itop-files-information:3.1.0, itop-portal-base:3.1.0, itop-portal:3.1.0, itop-profiles-itil:3.1.0, itop-sla-computation:3.1.0, itop-structure:3.1.0, itop-themes-compat:3.1.0, itop-tickets:3.1.0, itop-welcome-itil:3.1.0, authent-token:2.1.1, combodo-db-tools:3.1.0, itop-config-mgmt:3.1.0, itop-core-update:3.1.0, itop-datacenter-mgmt:3.1.0, itop-endusers-devices:3.1.0, itop-faq-light:3.1.0, itop-hub-connector:3.1.0, itop-incident-mgmt-itil:3.1.0, itop-knownerror-mgmt:3.1.0, itop-oauth-client:3.1.0, itop-problem-mgmt:3.1.0, itop-request-mgmt-itil:3.1.0, itop-service-mgmt-provider:3.1.0, itop-storage-mgmt:3.1.0, itop-virtualization-mgmt:3.1.0, teemip-framework:3.1.2, teemip-network-mgmt:3.1.1, combodo-webhook-integration:1.3.1, itop-bridge-cmdb-services:3.1.0, itop-bridge-cmdb-ticket:3.1.0, itop-bridge-datacenter-mgmt-services:3.1.0, itop-bridge-endusers-devices-services:3.1.0, itop-bridge-storage-mgmt-services:3.1.0, itop-bridge-virtualization-mgmt-services:3.1.0, itop-bridge-virtualization-storage:3.1.0, itop-change-mgmt-itil:3.1.0, itop-full-itil:3.1.0, teemip-ip-mgmt:3.1.1, teemip-ipv6-mgmt:3.1.1, teemip-newsroom-provider:1.1.2, teemip-webservices:3.0.0, teemip-zone-mgmt:3.0.1, teemip-config-mgmt-adaptor:3.1.0, teemip-datacenter-mgmt-adaptor:3.1.0, teemip-endusers-devices-adaptor:3.1.0, teemip-network-mgmt-extended:3.0.1`

**Comment by xtophe38** [comment]
Hi,

Please, use version 3.1.1 of TeemIP Network Management Extended and version 3.1.3 of IPAM for iTop. That should do it.

**Comment by snapet** [comment]
Thanks xtophe38!
That was of course it. Sorry for the noise!

And thanks for your work on this, it makes a lot of people's lives a lot easier.
